<?php

namespace App\Http\Requests\News;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => ['required', 'string', 'min:3', 'max:100'],
            'author' => ['required', 'string', 'min:3', 'max:50'],
            'status' => ['required', 'string', 'min:4', 'max:8'],
            'isImage' => ['nullable', 'boolean'],
            'image' => ['nullable', 'file', 'image', 'mimes:jpg, png'],
            'description' => ['nullable', 'string']
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
